{{ if .Values.podSecurityPolicyClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.name }}-{{ .Values.podSecurityPolicyClusterRole}}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if and .Values.rolebinding .Values.rolebinding.annotations }}
{{ .Values.rolebinding.annotations | toYaml | indent 4 }}
    {{ end }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.rolebinding .Values.rolebinding.labels }}
{{ .Values.rolebinding.labels | toYaml | indent 4 }}
    {{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.podSecurityPolicyClusterRole }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubelet
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:kube-system
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:{{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
  annotations:
    {{ if and .Values.clusterrole .Values.clusterrole.annotations }}
{{ .Values.clusterrole.annotations | toYaml | indent 4 }}
    {{ end }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.clusterrole .Values.clusterrole.labels }}
{{ .Values.clusterrole.labels | toYaml | indent 4 }}
    {{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
  annotations:
    {{ if and .Values.clusterrolebinding .Values.clusterrolebinding.annotations }}
{{ .Values.clusterrolebinding.annotations | toYaml | indent 4 }}
    {{ end }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.clusterrolebinding .Values.clusterrolebinding.labels }}
{{ .Values.clusterrolebinding.labels | toYaml | indent 4 }}
    {{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if and .Values.serviceaccount .Values.serviceaccount.annotations }}
{{ .Values.serviceaccount.annotations | toYaml | indent 4 }}
    {{ end }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.serviceaccount .Values.serviceaccount.labels }}
{{ .Values.serviceaccount.labels | toYaml | indent 4 }}
    {{ end }}
