apiVersion: v1  
kind: Service  
metadata:  
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if and .Values.service .Values.service.annotations }}
{{ .Values.service.annotations | toYaml | indent 4 }}
    {{ end }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.service .Values.service.labels }}
{{ .Values.service.labels | toYaml | indent 4 }}
    {{ end }}
spec:  
  ports:  
  - port: 8443  
    targetPort: 8443  
  selector:  
    app: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    {{ if and .Values.deployment .Values.deployment.annotations }}
{{ .Values.deployment.annotations | toYaml | indent 4 }}
    {{ end }}
  labels:
    app: {{ .Release.Name }}
    {{ if and .Values.deployment .Values.deployment.labels }}
{{ .Values.deployment.labels | toYaml | indent 4 }}
    {{ end }}
spec:
  replicas: {{ if .Values.leaderElection.enabled }}2{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        {{ if and .Values.pod .Values.pod.annotations }}
{{ .Values.pod.annotations | toYaml | indent 8 }}
        {{ end }}
      labels:
        app: {{ .Release.Name }}
        {{ if and .Values.pod .Values.pod.labels }}
{{ .Values.pod.labels | toYaml | indent 8 }}
        {{ end }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      {{- if .Values.leaderElection.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: {{ .Release.Name }}
{{ if .Values.kubeletConfig }}
{{ if .Values.kubeletConfig.binDir }}
      - name: kubelet-bindir
        hostPath:
          path: {{ .Values.kubeletConfig.binDir }}
{{ end }}
{{ if .Values.kubeletConfig.config }}
      - name: kubelet-configdir
        hostPath:
          path: {{ .Values.kubeletConfig.configDir }}
{{ end }}
{{ end }}
{{ range $i, $path := .Values.dockerConfigPathCandidates }}
      - name: docker-config-{{ $i }}
        hostPath:
          path: {{ $path }}
          type: File
{{ end }}
{{ range $i, $path := .Values.containerdConfigPathCandidates }}
      - name: containerd-config-{{ $i }}
        hostPath:
          path: {{ $path }}
{{ end }}
      containers:
      - name: webhook
        image: {{ .Values.image.registry }}/{{.Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        workingDir: /workdir
        args:
        - --registry-proxies={{ .Values.proxies | join "," }}
        - --cluster-schedulable-archs={{ .Values.schedulableArchitectures | join "," }}
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect=true
        {{- end }}
{{ if and .Values.kubeletConfig .Values.kubeletConfig.binDir }}
        - --image-credential-provider-bin-dir={{ .Values.kubeletConfig.binDir }}
{{ end }}
{{ if and .Values.kubeletConfig .Values.kubeletConfig.configDir }}
        - --image-credential-provider-config={{ .Values.kubeletConfig.configDir }}/{{ .Values.kubeletConfig.config }}
{{ end }}
{{ if .Values.privateRegistries }}
        - --private-registries={{ .Values.privateRegistries | join "," }}
{{ end }}
        ports:
        - containerPort: 8443
          name: webhook
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: certs
          mountPath: /workdir
          readOnly: true
{{ if .Values.kubeletConfig }}
{{ if .Values.kubeletConfig.binDir }}
        - name: kubelet-bindir
          mountPath: {{ .Values.kubeletConfig.binDir }}
          readOnly: true
{{ end }}
{{ if and .Values.kubeletConfig.configDir (ne .Values.kubeletConfig.configDir .Values.kubeletConfig.binDir) }}
        - name: kubelet-configdir
          mountPath: {{ .Values.kubeletConfig.configDir }}
          readOnly: true
{{ end }}
{{ end }}
{{ range $i, $path := .Values.dockerConfigPathCandidates }}
        - name: docker-config-{{ $i }}
          mountPath: {{ $path }}
          readOnly: true
{{ end }}
{{ range $i, $path := .Values.containerdConfigPathCandidates }}
        - name: containerd-config-{{ $i }}
          mountPath: {{ $path }}
          readOnly: true
{{ end }}
